# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\x0bsmartcampus\"\"\n\x0f\x41mbienteRequest\x12\x0f\n\x07sala_id\x18\x01 \x01(\x05\"`\n\x10\x41mbienteResponse\x12\x0c\n\x04nome\x18\x01 \x01(\t\x12\x13\n\x0btemperatura\x18\x02 \x01(\x02\x12\x10\n\x08presenca\x18\x03 \x01(\x08\x12\x17\n\x0f\x61r_condicionado\x18\x04 \x01(\t\"5\n\x11\x43ontroleArRequest\x12\x0f\n\x07sala_id\x18\x01 \x01(\x05\x12\x0f\n\x07\x63omando\x18\x02 \x01(\t\"$\n\x12\x43ontroleArResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2\xc0\x01\n\x0f\x41mbienteService\x12Q\n\x12ObterDadosAmbiente\x12\x1c.smartcampus.AmbienteRequest\x1a\x1d.smartcampus.AmbienteResponse\x12Z\n\x17\x43ontrolarArCondicionado\x12\x1e.smartcampus.ControleArRequest\x1a\x1f.smartcampus.ControleArResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AMBIENTEREQUEST']._serialized_start=30
  _globals['_AMBIENTEREQUEST']._serialized_end=64
  _globals['_AMBIENTERESPONSE']._serialized_start=66
  _globals['_AMBIENTERESPONSE']._serialized_end=162
  _globals['_CONTROLEARREQUEST']._serialized_start=164
  _globals['_CONTROLEARREQUEST']._serialized_end=217
  _globals['_CONTROLEARRESPONSE']._serialized_start=219
  _globals['_CONTROLEARRESPONSE']._serialized_end=255
  _globals['_AMBIENTESERVICE']._serialized_start=258
  _globals['_AMBIENTESERVICE']._serialized_end=450
# @@protoc_insertion_point(module_scope)
