# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import service_pb2 as service__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AmbienteServiceStub(object):
    """Define o serviço gRPC
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ObterDadosAmbiente = channel.unary_unary(
                '/smartcampus.AmbienteService/ObterDadosAmbiente',
                request_serializer=service__pb2.AmbienteRequest.SerializeToString,
                response_deserializer=service__pb2.AmbienteResponse.FromString,
                _registered_method=True)
        self.ControlarArCondicionado = channel.unary_unary(
                '/smartcampus.AmbienteService/ControlarArCondicionado',
                request_serializer=service__pb2.ControleArRequest.SerializeToString,
                response_deserializer=service__pb2.ControleArResponse.FromString,
                _registered_method=True)


class AmbienteServiceServicer(object):
    """Define o serviço gRPC
    """

    def ObterDadosAmbiente(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ControlarArCondicionado(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AmbienteServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ObterDadosAmbiente': grpc.unary_unary_rpc_method_handler(
                    servicer.ObterDadosAmbiente,
                    request_deserializer=service__pb2.AmbienteRequest.FromString,
                    response_serializer=service__pb2.AmbienteResponse.SerializeToString,
            ),
            'ControlarArCondicionado': grpc.unary_unary_rpc_method_handler(
                    servicer.ControlarArCondicionado,
                    request_deserializer=service__pb2.ControleArRequest.FromString,
                    response_serializer=service__pb2.ControleArResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'smartcampus.AmbienteService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('smartcampus.AmbienteService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AmbienteService(object):
    """Define o serviço gRPC
    """

    @staticmethod
    def ObterDadosAmbiente(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/smartcampus.AmbienteService/ObterDadosAmbiente',
            service__pb2.AmbienteRequest.SerializeToString,
            service__pb2.AmbienteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ControlarArCondicionado(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/smartcampus.AmbienteService/ControlarArCondicionado',
            service__pb2.ControleArRequest.SerializeToString,
            service__pb2.ControleArResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
